imports:
    timezone_dump:
        resource: timezones.yml

services:
    bert.timezone.form.type.readabletimezone:
        class: Bert\TimezoneBundle\Form\ReadableTimezoneType
        arguments: [%bert.timezones.timezone_data%]
        tags:
            - { name: form.type, alias: readabletimezone }